steps:
- id: 'Build-Docker-Image'
  name: 'gcr.io/cloud-builders/docker'
  dir: 'src/${_IMAGE}'
  args: ['build',
         '-t', '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_NAME}/${_IMAGE}:latest',
         '-f', 'Dockerfile',
         '.']

substitutions:
  _AR_NAME: tools # default value
  _AR_REGION: us-east4 # default value
  _IMAGE: cloudrun-deploy-to-k8s # default value

images:
- '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_NAME}/${_IMAGE}:latest'
