apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-api-proxy
  template:
    metadata:
      labels:
        app: k8s-api-proxy
    spec:
      containers:
      - name: k8s-api-proxy
        image: IMAGE
        ports:
          - containerPort: 8118
